# Generated by Django 5.2.12 on 2026-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_logic', models.FloatField(default=0.0)),
                ('required_creativity', models.FloatField(default=0.0)),
                ('required_social', models.FloatField(default=0.0)),
                ('required_verbal', models.FloatField(default=0.0)),
            ],
        ),
    ]
