# Generated by Django 5.2.12 on 2026-04-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('school', 'School'), ('stream', 'Stream'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('career', 'Career'), ('specialization', 'Specialization')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('required_skills', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.careernode')),
            ],
        ),
    ]
