# Generated by Django 5.2.12 on 2026-03-31 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_reasoning', models.FloatField(default=0.0)),
                ('verbal_ability', models.FloatField(default=0.0)),
                ('numerical_aptitude', models.FloatField(default=0.0)),
                ('spatial_reasoning', models.FloatField(default=0.0)),
                ('memory_retention', models.FloatField(default=0.0)),
                ('processing_speed', models.FloatField(default=0.0)),
                ('openness', models.FloatField(default=0.0)),
                ('conscientiousness', models.FloatField(default=0.0)),
                ('extraversion', models.FloatField(default=0.0)),
                ('agreeableness', models.FloatField(default=0.0)),
                ('neuroticism', models.FloatField(default=0.0)),
                ('realistic', models.FloatField(default=0.0)),
                ('investigative', models.FloatField(default=0.0)),
                ('artistic', models.FloatField(default=0.0)),
                ('social', models.FloatField(default=0.0)),
                ('enterprising', models.FloatField(default=0.0)),
                ('conventional', models.FloatField(default=0.0)),
                ('leadership', models.FloatField(default=0.0)),
                ('teamwork', models.FloatField(default=0.0)),
                ('creativity', models.FloatField(default=0.0)),
                ('resilience', models.FloatField(default=0.0)),
                ('empathy', models.FloatField(default=0.0)),
                ('risk_appetite', models.FloatField(default=0.0)),
                ('attention_to_detail', models.FloatField(default=0.0)),
                ('communication', models.FloatField(default=0.0)),
                ('intrinsic_motivation', models.FloatField(default=0.0)),
                ('extrinsic_motivation', models.FloatField(default=0.0)),
                ('social_impact_drive', models.FloatField(default=0.0)),
                ('autonomy_preference', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trait_vector', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(blank=True, max_length=50)),
                ('current_grade', models.CharField(blank=True, max_length=20)),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('strong_subjects', models.JSONField(blank=True, default=list)),
                ('weak_subjects', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('hobbies', models.JSONField(blank=True, default=list)),
                ('self_rated_skills', models.JSONField(blank=True, default=dict)),
                ('extracurriculars', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('achievements', models.TextField(blank=True)),
                ('career_goals', models.TextField(blank=True)),
                ('preferred_work_env', models.CharField(blank=True, max_length=50)),
                ('location_preference', models.CharField(blank=True, max_length=100)),
                ('willing_to_relocate', models.BooleanField(default=True)),
                ('self_description', models.TextField(blank=True)),
                ('proud_of', models.TextField(blank=True)),
                ('ideal_day', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
