# Generated by Django 5.2.12 on 2026-03-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('logic_weight', models.FloatField(default=0.0)),
                ('creative_weight', models.FloatField(default=0.0)),
                ('social_weight', models.FloatField(default=0.0)),
                ('numerical_weight', models.FloatField(default=0.0)),
                ('communication_weight', models.FloatField(default=0.0)),
                ('industry_sector', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
