# Generated by Django 5.2.12 on 2026-03-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_career'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='communication_weight',
            new_name='target_communication',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='creative_weight',
            new_name='target_creativity',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='logic_weight',
            new_name='target_logic',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='numerical_weight',
            new_name='target_numerical',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='social_weight',
            new_name='target_social',
        ),
        migrations.RemoveField(
            model_name='career',
            name='industry_sector',
        ),
        migrations.AddField(
            model_name='career',
            name='industry',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='min_education',
            field=models.CharField(choices=[('school', 'School'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate')], default='ug', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='target_verbal',
            field=models.FloatField(default=0.0),
        ),
    ]
