# Generated by Django 5.2.12 on 2026-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_rename_communication_weight_career_target_communication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='target_creativity',
            new_name='target_artistic',
        ),
        migrations.AddField(
            model_name='career',
            name='target_conventional',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='career',
            name='target_enterprising',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='career',
            name='target_investigative',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='career',
            name='target_leadership',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='career',
            name='target_realistic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='career',
            name='target_spatial',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='career',
            name='target_teamwork',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='career',
            name='min_education',
            field=models.CharField(choices=[('10th', '10th Standard'), ('12th', '12th Standard'), ('UG', 'Undergraduate')], max_length=50),
        ),
    ]
