# Generated by Django 5.2.12 on 2026-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_rename_target_creativity_career_target_artistic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location_preference',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proud_of',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='willing_to_relocate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_biology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_commerce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_maths',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='board',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE', 'State Board'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stream',
            field=models.CharField(blank=True, choices=[('science_pcm', 'Science (PCM)'), ('science_pcb', 'Science (PCB)'), ('science_pcmb', 'Science (PCMB)'), ('commerce', 'Commerce'), ('arts', 'Arts/Humanities'), ('other', 'Other')], max_length=30),
        ),
    ]
