# Generated by Django 5.2.12 on 2026-03-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_remove_userprofile_achievements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='preferred_work_env',
            new_name='institution_type',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='percentage',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='current_grade',
            new_name='score_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='board',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='career_goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='extracurriculars',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ideal_day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='self_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weak_subjects',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('school_low', 'Class 6–10'), ('school_high', 'Class 11–12'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('working', 'Working Professional')], max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stream',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
