# Generated by Django 5.2.12 on 2026-04-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_rename_preferred_work_env_userprofile_institution_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='postgraduate_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_high_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_low_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='undergraduate_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_completed',
            field=models.BooleanField(default=False),
        ),
    ]
