# Generated by Django 5.2.12 on 2026-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0007_userprofile_postgraduate_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, choices=[('ba', 'Bachelor of Arts'), ('bsc', 'Bachelor of Science'), ('bcom', 'Bachelor of Commerce'), ('btech', 'B.Tech / B.E.'), ('mbbs', 'Medicine (MBBS)'), ('bds', 'Dental Surgery (BDS)'), ('other', 'Other')], max_length=50),
        ),
    ]
