# Generated by Django 5.2.12 on 2026-04-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0008_alter_userprofile_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='roadmap_steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
