# Generated by Django 5.2.12 on 2026-04-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='trait_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('scores', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.question')),
            ],
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.option'),
        ),
    ]
