# Generated by Django 5.2.12 on 2026-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('cognitive', 'Cognitive'), ('emotional', 'Emotional'), ('behavioral', 'Behavioral'), ('personality', 'Personality')], default='behavioral', max_length=20),
        ),
    ]
