# Generated by Django 5.2.12 on 2026-04-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='option',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
